import { chromium } from '@playwright/test';
import { preview } from 'vite';
import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';
import { installOutputMeter } from './audio-probe.mjs';

let browser, server, passed = 0;
const check = (name, value) => { assert.ok(value, name); passed++; console.log('PASS library: ' + name); };
try {
  server = await preview({ preview: { host: '127.0.0.1', port: 4182, strictPort: true } });
  browser = await chromium.launch(); const page = await browser.newPage(); const errors = [];
  page.on('pageerror', error => errors.push(error.message)); await page.addInitScript(installOutputMeter);
  await page.goto('http://127.0.0.1:4182/');
  const ready = () => page.getByTestId('engine-state').filter({ hasText: 'ready' }).waitFor({ timeout: 60000 });
  const library = () => page.getByRole('tab', { name: 'library', exact: true }).click();
  const button = text => page.getByRole('button', { name: text });
  await ready();
  check('guide has no close X', await page.getByRole('button', { name: 'Hide help panel' }).count() === 0);
  await page.getByTestId('mode-toggle').click();
  check('advanced hides the guide', await page.getByRole('complementary', { name: 'Beginner help' }).count() === 0 && await page.getByTestId('mode-toggle').getAttribute('aria-pressed') === 'false');
  await page.getByTestId('mode-toggle').click();
  check('one click reopens beginner guide', await page.getByRole('tab', { name: 'guide', exact: true }).isVisible());
  await page.getByTestId('mode-toggle').click(); await page.keyboard.press('F1');
  check('HELP and top toggle share the same state', await page.getByTestId('mode-toggle').getAttribute('aria-pressed') === 'true');
  await library();
  const melody = '$: note("c4 e4 g4").s("triangle").gain(0.1)';
  await page.getByLabel('Starter name').fill('My gentle melody'); await page.getByLabel('Starter code').fill(melody);
  await button(/save starter/).click();
  check('saving a melody does not run it', !(await page.getByTestId('engine-state').innerText()).includes('playing'));
  check('saved starter is listed', await button('Load My gentle melody').count() === 1);
  await page.getByLabel('Find my starters').fill('gentle');
  check('search finds starter', await page.locator('.personal-library .melody-card').count() === 1);
  await page.getByLabel('Find my starters').fill('no-such-starter');
  check('search supports no matches', await page.locator('.personal-library .melody-card').count() === 0);
  await page.getByLabel('Find my starters').fill('');
  const downloadPromise = page.waitForEvent('download'); await button(/export library/).click();
  const download = await downloadPromise; const exported = JSON.parse(await readFile(await download.path(), 'utf8'));
  check('export downloads versioned library JSON', exported.version === 1 && exported.entries[0].code === melody);
  const importFile = async data => page.getByTestId('library-import').setInputFiles({ name: 'library.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(data)) });
  await importFile({ ...exported, entries: [{ ...exported.entries[0], title: 'Imported melody' }, { id: 'ruby', title: 'Ruby starter', engine: 'sonic-pi', code: 'play 60' }] });
  await page.getByRole('status').filter({ hasText: 'Library imported' }).waitFor();
  check('import preserves original with colliding ID', await button('Load My gentle melody').count() === 1 && await button('Load Imported melody').count() === 1);
  check('other-engine code is preserved without appearing as Strudel', await button('Load Ruby starter').count() === 0 && await page.evaluate(() => JSON.parse(localStorage.getItem('beatexe.library.v1')).entries.some(entry => entry.engine === 'sonic-pi')));
  await importFile({ version: 99 }); await page.getByRole('status').filter({ hasText: 'Import failed' }).waitFor();
  check('invalid import keeps library intact', await page.locator('.personal-library .melody-card').count() === 2);
  await button('Load My gentle melody').click();
  check('load opens a new project tab without playback', await page.getByTestId('project-name').innerText().then(text => text.includes('My gentle melody')) && !(await page.getByTestId('engine-state').innerText()).includes('playing'));
  const original = await page.locator('.cm-content').innerText();
  await button('Insert Imported melody').click(); await page.locator('.cm-content').press('Control+z');
  check('library insertion is a separate undo step', await page.locator('.cm-content').innerText() === original);
  await button(/copy from editor/).click(); check('copy uses current editor code', await page.getByLabel('Starter code').inputValue() === original);
  await page.getByTestId('btn-run').click(); await page.waitForFunction(() => window.__levels.nonzero > 0, undefined, { timeout: 20000 });
  check('saved melody plays through real Strudel', await page.evaluate(() => window.__levels.peak > 0));
  await page.getByTestId('btn-stop').click(); await ready();
  await button('Delete starter Imported melody').click(); await button('Keep starter').click();
  check('cancel deletion preserves starter', await button('Load Imported melody').count() === 1);
  await button('Delete starter Imported melody').click(); await button('Confirm delete starter').click();
  check('confirmed deletion preserves open code', await button('Load Imported melody').count() === 0 && await page.locator('.cm-content').innerText() === original);
  await page.reload(); await ready(); await library();
  check('saved library survives reload', await button('Load My gentle melody').count() === 1);
  for (const width of [320, 390]) {
    await page.setViewportSize({ width, height: 844 });
    check(`${width}px library has no horizontal overflow`, await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth && document.querySelector('.panel-body').scrollWidth <= document.querySelector('.panel-body').clientWidth));
  }
  await mkdir('tests/smoke/artifacts', { recursive: true }); await page.locator('.side-panel').screenshot({ path: 'tests/smoke/artifacts/library-mobile.png' });
  await page.evaluate(() => { const original = Storage.prototype.setItem; Storage.prototype.setItem = function(key, value) { if (key === 'beatexe.library.v1') throw new Error('Storage full'); return original.call(this, key, value); }; });
  await page.getByLabel('Starter name').fill('Cannot save'); await page.getByLabel('Starter code').fill('note("c4")'); await button(/save starter/).click();
  check('quota failure is explained without losing existing starters', (await page.locator('.personal-library').innerText()).includes('Could not save') && await button('Load My gentle melody').count() === 1);
  check('no renderer errors', errors.length === 0);
  console.log(`${passed}/${passed} library/help checks passed (real production browser)`);
} finally { if (browser) await browser.close(); if (server) await new Promise(resolve => server.httpServer.close(resolve)); }
