// Integration checks against the unaliased production build. No sound assertion.
import { chromium } from '@playwright/test';
import { preview } from 'vite';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const server = await preview({ preview: { host: '127.0.0.1', port: 4174, strictPort: true } });
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
const errors = [];
const warnings = [];
const messages = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', m => { messages.push(m.text()); if(m.type() === 'error') errors.push(m.text()); if(m.type() === 'warning') warnings.push(m.text()); });
let passed = 0;
const check = (name, value) => { assert.ok(value, name); console.log(`PASS  real: ${name}`); passed++; };
const content = page.locator('.cm-content');
const code = async value => { await content.press('Control+Home'); await content.press('Control+a'); await page.keyboard.insertText(value); };
const log = page.getByTestId('terminal-log');
const state = page.getByTestId('engine-state');
const ready = () => state.filter({hasText:'ready'}).waitFor({timeout:60000});
try {
  await page.goto('http://127.0.0.1:4174/');
  await ready();
  check('CodeMirror rendered', await page.locator('.cm-editor').count() === 1);
  // First interaction is keyboard; no mouse action has happened.
  await content.press('Control+Enter');
  await state.filter({hasText:'playing'}).waitFor();
  await page.waitForTimeout(1500);
  check('keyboard first RUN loads audio worklets', messages.some(m=>m.includes('AudioWorklets loaded')));
  await content.press('Control+.');
  await ready();
  check('keyboard STOP returns ready', (await state.innerText()).includes('ready'));
  await code('$: note("c3 e3 g3").s("sawtooth")');
  await content.press('Control+Enter');
  await state.filter({hasText:'playing'}).waitFor();
  check('real synth evaluates', !(await log.innerText()).includes('ERROR DETECTED'));
  await content.press('Control+.');
  await content.press('Control+f');
  check('real search panel opens', await page.locator('.cm-search').count() === 1);
  await page.locator('.cm-search input[name=search]').fill('sawtooth');
  await page.locator('.cm-search input[name=replace]').fill('sine');
  await page.getByRole('button',{name:'replace all',exact:true}).click();
  check('real replace changes document', (await content.innerText()).includes('s("sine")'));
  await content.press('Escape');
  await content.press('Control+z');
  check('real undo restores code', (await content.innerText()).includes('sawtooth'));
  await content.press('Control+Shift+Z');
  check('real redo restores replacement', (await content.innerText()).includes('s("sine")'));
  await code('s("bd").');
  await content.press('Control+Space');
  await page.locator('.cm-tooltip-autocomplete').waitFor();
  check('real method completion appears', (await page.locator('.cm-tooltip-autocomplete').innerText()).includes('gain'));
  await content.press('ArrowDown');
  await page.locator('.cm-completionInfo').waitFor();
  check('real completion explanation appears', (await page.locator('.cm-completionInfo').innerText()).length > 10);
  await content.press('Escape');
  for (const id of ['first-beat','drum-groove','bassline','melody','chords','full-track']) {
    await page.getByTestId('terminal-input').fill(`load ${id}`);
    await page.getByTestId('terminal-input').press('Enter');
    if(await page.getByTestId('dialog-confirm').count()) await page.getByTestId('dialog-confirm').click();
    await page.getByTestId('btn-run').click();
    await state.filter({hasText:'playing'}).waitFor();
    await page.waitForTimeout(2500);
    check(`example ${id} evaluates without reported runtime errors`, !(await log.innerText()).includes('ERROR'));
    await page.getByTestId('btn-stop').click();
  }
  check('no missing sound or sample failure logs', !messages.some(m=>/not found|could not load|error:/i.test(m)));
  await code('$: note("c3").s("sine")');
  await content.press('Control+Enter');
  await state.filter({hasText:'playing'}).waitFor();
  for(let i = 0; i < 5; i++) await content.press('Control+Enter');
  await page.waitForTimeout(500);
  check('rapid real updates keep playing', (await state.innerText()).includes('playing'));
  check('no unexpected errors before deliberate bad code', errors.length === 0);
  const errorCount = errors.length;
  await code('$: s("bd")\nBROKEN(((');
  await page.getByTestId('btn-run').click();
  await log.filter({hasText:'ERROR DETECTED'}).waitFor();
  check('real syntax error gets a friendly explanation', (await log.innerText()).includes('around line 2'));
  check('real syntax error marks line', await page.locator('.cm-beat-error-line').count() === 1);
  check('real syntax error keeps prior playback state', (await state.innerText()).includes('playing'));
  // Upstream deliberately console.error's eval errors; these are expected.
  check('only expected syntax error was logged', errors.slice(errorCount).every(m=>/Unexpected token|SyntaxError/i.test(m)));
  errors.splice(errorCount);
  await code('$: note("c3").s("sine")');
  await page.getByTestId('btn-run').click();
  await page.locator('.cm-beat-error-line').waitFor({state:'detached'});
  check('real evaluation recovers', (await state.innerText()).includes('playing'));
  await page.getByTestId('btn-stop').click();
  // Command palette operates on the real editor and existing app actions.
  await content.focus();
  await page.keyboard.press('Control+Shift+P');
  const palette=page.getByTestId('command-palette');
  const query=page.getByTestId('palette-input');
  await palette.waitFor();
  check('palette shortcut opens from real editor',await query.evaluate(el=>el===document.activeElement));
  await query.fill('th am');
  check('palette fuzzy search finds Amber CRT',await palette.locator('[aria-selected=true]').innerText().then(t=>t.includes('Amber CRT')));
  await query.press('Enter');
  await palette.waitFor({state:'detached'});
  check('palette theme action persists',await page.evaluate(()=>JSON.parse(localStorage.getItem('beatexe.settings.v1')).themeId==='amber'));
  await content.focus();await page.keyboard.press('Control+Shift+P');await query.press('Escape');
  check('palette cancellation restores editor focus',await content.evaluate(el=>el===document.activeElement));
  await page.getByTestId('btn-palette').click();await query.fill('sonic');
  const unavailable=palette.locator('[data-palette-id="engine:sonic-pi"]');
  check('unimplemented engine disabled in palette',await unavailable.getAttribute('aria-disabled')==='true');
  await unavailable.click({force:true});
  check('disabled action keeps palette open',await palette.isVisible());
  await query.fill('zzzzzzzzzz');await query.press('Enter');
  check('empty search cannot execute an action',await palette.isVisible() && await palette.getByRole('option').count()===0);
  await query.fill('set');await palette.locator('[data-palette-id="command:set"]').click();
  check('argument command prepares terminal input',await page.getByTestId('terminal-input').inputValue()==='set ');
  check('prepared command focuses terminal',await page.getByTestId('terminal-input').evaluate(el=>el===document.activeElement));
  await page.getByTestId('terminal-input').fill('');
  await content.focus();await page.keyboard.press('Control+Shift+P');
  await query.fill('save');await palette.locator('[data-palette-id="command:save"]').click();
  await page.getByTestId('dialog').waitFor();
  check('palette save opens existing name dialog',await page.getByTestId('dialog').isVisible());
  await page.getByTestId('dialog-input').fill('palette-test');await page.getByTestId('dialog-confirm').click();
  await page.getByTestId('btn-palette').click();await query.fill('delete project palette-test');
  await palette.getByRole('option').first().click();
  check('palette delete requires existing confirmation',(await page.getByTestId('dialog').innerText()).includes('cannot be undone'));
  await page.keyboard.press('Escape');
  check('cancelled palette delete preserves project',await page.evaluate(()=>JSON.parse(localStorage.getItem('beatexe.projects.v1')).some(p=>p.name==='palette-test')));
  await mkdir('tests/smoke/artifacts',{recursive:true});
  await page.screenshot({path:'tests/smoke/artifacts/real-desktop.png'});
  for(const width of [390,320]) {
    await page.setViewportSize({width,height:800});
    check(`mobile ${width}px has no horizontal overflow`, await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth));
    check(`mobile ${width}px editor visible`, await content.isVisible());
  }
  await page.screenshot({path:'tests/smoke/artifacts/real-mobile.png',fullPage:true});
  await page.getByTestId('btn-palette').click();await query.fill('theme');
  check('mobile palette fits viewport',await palette.evaluate(el=>el.getBoundingClientRect().right<=innerWidth && el.getBoundingClientRect().left>=0));
  await page.screenshot({path:'tests/smoke/artifacts/palette-mobile.png',fullPage:true});await query.press('Escape');
  check('no unexpected console or page errors', errors.length === 0);
  check('no worklet warnings', !warnings.some(w=>/worklet/i.test(w)));
  console.log(`${passed}/${passed} real production checks passed (audio audibility unverified)`);
} finally { await browser.close(); await new Promise(r=>server.httpServer.close(r)); }
